### PR TITLE
Modified the code to allow balancing of the bet to the user

### LINKED ISSUE #1: Unbalanced
The game is unbalanced,

It favors the house too much, maybe if you win you dont lose the money you bet? So now it becomes more fair... as most bets even when won give 2/3 of what you betted on...

### PR DESCRIPTION
**Pull request by DefinetlyNotAI**
The user now gets his bet money back if he wins the slot machine turn, this is to balance the game.

### CODE REVIEW

**Comment by DefinetlyNotAI** [comment]
You may add to the Developement in the right side of this PR the issue i have opened, then you can if you want test it, check it works, and then close the issue and merge the branch :)

**Comment by Daniel-dev-s** [comment]
OK, have you tested it already? Doesnt player need to reset bet after each spin now?

**Comment by DefinetlyNotAI** [comment]
I am very sorry, but can you tell me how to test it, again im not really good with C, but yes i did make it reset the bet, but its only one line so you may remove it,

**Comment by DefinetlyNotAI** [comment]
Done, i have commented that line of code, just incase bugs are found

**Comment by Daniel-dev-s** [comment]
you need to clone `flipperzero-firmware` repo, put this plugin into `applications_user` folder and then build it with `./fbt launch APPSRC=applications_user/flipperzero-slots` with connected flipper. But i dont think your PR can really damage anything, so i merge)

**Comment by Daniel-dev-s** [comment]
its been so long since i used this dev tools for flipper) I need to check it again someday)

**Comment by DefinetlyNotAI** [comment]
> you need to clone `flipperzero-firmware` repo, put this plugin into `applications_user` folder and then build it with `./fbt launch APPSRC=applications_user/flipperzero-slots` with connected flipper. But i dont think your PR can really damage anything, so i merge)

Thanks for the tip, I am new to the flipper zero, and love testing it, but yeah, i will learn more abt, thx, :)

**Comment by DefinetlyNotAI** [comment]
Just a quick question, can i update this via the flipper app? or do i need to do what you said,

**Comment by Daniel-dev-s** [comment]
Unfortunately u need to build it and install on your own, because apps in 'flipper app' are supported and updated by the guy who created this firmware. May be if we make significant changes, he will update it again)

**Comment by DefinetlyNotAI** [comment]
> Unfortunately u need to build it and install on your own, because apps in 'flipper app' are supported and updated by the guy who created this firmware. May be if we make significant changes, he will update it again)

Oh, ok, thanks though

**Comment by DefinetlyNotAI** [comment]
just found out it updated :)

**Comment by DefinetlyNotAI** [comment]
in the actual app store

**Pull request merged**
